# Generated by Django 4.1.7 on 2023-03-23 01:40

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço')),
                ('contato', models.IntegerField(verbose_name='telefone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Produto')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='produto', variations={'thumb': (124, 123)}, verbose_name='Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
